import type { Metadata } from "next";
import { Inter, Karla } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/SideBar";
import Header from "@/components/Header";
import PageWrapper from "@/components/PageWrapper";

const inter = Inter({ subsets: ["latin"] });

const karla = Karla({
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
  variable: "--font-karla"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SideBar></SideBar>
        <Header></Header>
        <PageWrapper>{children}</PageWrapper>
      </body>
    </html>
  );
}
